### ISSUE TITLE
Congratulations!!

### ISSUE THREAD

**Issue by vmarcosp** [doesangueorg/doesangue-webapp#7]
Congratulations for this project, really is a GREAT idea!! The world need projects that help people!! If u need any help, i'm interested in help you! :smile:

**Comment by JoseCage** [comment]
> Congratulations for this project, really is a GREAT idea!! The world need projects that help people!! If u need any help, i'm interested in help you!

Oh thanks @vmarcosp 

The project is split between [core](https://github.com/doesangueorg/doesangue-core), [android app](https://github.com/doesangueorg/android), spa ([web app](https://github.com/doesangueorg/doesangue-webapp)) and I preferred to leave everything opensource, so that more people can help me develop the project as more people can use the project in any way they want or need.

**Comment by JoseCage** [comment]
At this moment, taking into account that the backend is a few steps further, I need the maximum help possible to be able to move forward with the landingpage and the webapp, and so launch the project on the internet / search for partnerships, etc. If I can to help of some I will be very grateful.

**Comment by vmarcosp** [comment]
Of course @JoseCage, i'm a full stack developer focused in front-end development. I see that the webapp spa use VueJS, i have experience with vuejs and can contribute :smile:

**Comment by JoseCage** [comment]
> Of course @JoseCage, i'm a full stack developer focused in front-end development. I see that the webapp spa use VueJS, i have experience with vuejs and can contribute

So good.. Take a look at open [**issues**](https://github.com/doesangueorg/doesangue-webapp/issues) and basically you will understand some tasks to be *resolved*. Thanks again..
